### ISSUE TITLE
DRS: PVnet backtest

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-nia-drs#5]
Run PVnet net from 2017 to 2023-05. 

- Get backtests results
- Mix together with National_xg

------
This is ready for 2020 onwards, that should be sent to SI first

**Comment by peterdudfield** [comment]
Uploaded to SI -  Did not include blending

**Comment by peterdudfield** [comment]
@zakwatts Ill keep this `In Progress` until you have merged/refactored the drs code

**Comment by zakwatts** [comment]
Sounds good

**Comment by zakwatts** [comment]
https://github.com/openclimatefix/uk-nia-drs/pull/9

**Comment by zakwatts** [comment]
@peterdudfield This has now been merged, happy to close.
